name: ca-amt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - joblib>=1.2
  - matplotlib>=3.6
  - numpy>=1.23
  - openpyxl>=3.1
  - pandas>=1.5
  - pillow>=9.0
  - scikit-learn>=1.2
  - scipy>=1.9
  - pytorch>=2.0
  - torchvision>=0.15
  - pip:
      - shap>=0.41
      - xgboost>=1.7

